# Generated by Django 5.1.1 on 2024-09-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='wishlist',
        ),
    ]
