# Generated by Django 5.1.1 on 2024-09-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_image_remove_products_image_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='images',
        ),
    ]
