# Generated by Django 5.1.1 on 2024-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_products_category_alter_products_title_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
