# Generated by Django 5.1.1 on 2024-10-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_products_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='user_id',
        ),
    ]
